spring.application.name=chronicle
spring.datasource.url=jdbc:mysql://localhost:3306/chronicle_db
spring.datasource.username=root
spring.datasource.password=root_riccardo17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver