spring.application.name=chronicle
spring.datasource.url=jdbc:mysql://localhost:3306/chronicle_db
spring.datasource.username=root
spring.datasource.password=root_riccardo17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mvc.hiddenmethod.filter.enabled=true

supabase.url=https://cfgcyvppdomxbojnmjqz.storage.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZ2N5dnBwZG9teGJvam5tanF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzU1NjUsImV4cCI6MjA5MTc1MTU2NX0.0whwjOdjECEVO3gzGNSC9QgfLDRMUfXdsciPBvqR4uA
supabase.bucket=/storage/v1/object/bucket_1/
supabase.image=/storage/v1/object/public/bucket_1/
spring.mail.host=localhost
spring.mail.port=1025

spring.mail.username=
spring.mail.password=

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false